---
title: "nimMCMCSMCupdates"
format: gfm
editor: visual
output: gfm
bibliography: vignette/references.bib
---

# Introduction

This package comes with a sequential Monte Carlo algorithm for data assimilation problems in ecology. This package is editted from the *nimbleSMC* package @michaud2021sequential, so the users of this package need to be familiar with the NIMBLE software through its R-package *nimble* [@nimblepackage] and then its R-package for sequential Monte Carlo problems *nimbleSMC* (the reader is referred to Chapter 8 of @nimblepackage and @michaud2021sequential for details on how to fit SSMs using SMC approach in NIMBLE). 

## Installation

You can install the development version of *nimMCMCSMCupdates* from [GitHub](https://github.com/) with:

```{r, echo=TRUE, eval=FALSE}
install.packages("devtools")
devtools::install_github("Peprah94/nimMCMCSMCupdates")
```


## Functions in the R-package

*nimMCMCSMCupdates* includes a set of functions that are used to update posterior distribution of latent states and model parameters using the bootstap and auxiliary particle filters. Refer to the [main paper][https://peprah94.github.io/#Publications] and vignette on [method][https://github.com/Peprah94/nimMCMCSMCupdates/blob/main/vignette/methodUnderstanding.pdf] for further details on the methodology.  







## Updating models with the R-package


## Other Materials

# References {.unnumbered}

::: {#refs}
:::